### 创建用户
POST localhost:8080/api/admin/users
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiRnI1ZyIsInVpZCI6IjE0MTc3NzYyMTMwMDEyOTc5MjAiLCJpYXQiOjE3NTgwOTUxOTYsImV4cCI6MTc1ODE4MTU5Nn0.tBLJpYNMI6w_QgwSwVNA6VpYWnEwBuzW30L_UKknNq0
Content-Type: application/json

{
  "name": "wuwenjin",
  "account": "666",
  "role": "yHJ7"
}

### 管理员重置密码  重置账号为 666
PUT localhost:8080/api/admin/users/666/password
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiRnI1ZyIsInVpZCI6IjE0MTc3NzYyMTMwMDEyOTc5MjAiLCJpYXQiOjE3NTgwOTUxOTYsImV4cCI6MTc1ODE4MTU5Nn0.tBLJpYNMI6w_QgwSwVNA6VpYWnEwBuzW30L_UKknNq0
Content-Type: application/json