### 辅导员登录
POST localhost:8080/api/open/login
Content-Type: application/json

{
  "account": "2046221540",
  "password": "2046221540"
}

> {% client.global.set("token", response.headers.valueOf("token")); %}