### 1. 学院管理员登录
POST localhost:8080/api/open/login
Content-Type: application/json

{
  "account": "2023221547",
  "password": "2023221547"
}

> {%
    // 保存token到环境变量
    client.global.set("token", response.headers.valueOf("token"));
    client.global.set("cid", response.body.data.collegeId);
    client.log("登录成功，token: " + client.global.get("token"));
    client.log("学院ID: " + client.global.get("cid"));
%}

### 2. 添加一级指标点（无父节点）
POST localhost:8080/api/collegeadmin/indicatorpoints
token: {{token}}
Content-Type: application/json

{
  "majorCategoryId": 101,
  "name": "学术能力",
  "description": "评估学生的学术研究能力",
  "maxScore": 40.0,
  "itemUpperLimit": 5
}

> {%
    client.global.set("rootPointId", response.body.data.id);
    client.log("创建一级指标点成功，ID: " + response.body.data.id);
%}

### 3. 添加二级指标点（有父节点）
POST localhost:8080/api/collegeadmin/indicatorpoints
token: {{token}}
Content-Type: application/json

{
  "majorCategoryId": 101,
  "name": "论文发表",
  "description": "评估学生论文发表情况",
  "maxScore": 20.0,
  "itemUpperLimit": 2,
  "parentId": {{rootPointId}}
}

> {%
    client.global.set("childPointId", response.body.data.id);
    client.log("创建二级指标点成功，ID: " + response.body.data.id);
%}

#### 4. 获取指标点树形结构
#GET localhost:8080/api/collegeadmin/indicatorpoints/tree?majorCategoryId=101
#token: {{token}}


### 获取树形结构
GET localhost:8080/api/collegeadmin/indicatorpoints/tree?majorCategoryId=101
token: {{token}}

> {%
    client.test("验证树形结构", function() {
        client.assert(response.status === 200, "请求成功");
        client.assert(response.body.data[0].children !== undefined, "应包含children字段");
        client.assert(response.body.data[0].children.length > 0, "应包含子节点");
    });
%}


#### 5. 获取指定节点的子节点
#GET localhost:8080/api/collegeadmin/indicatorpoints/{{rootPointId}}/children
#token: {{token}}

#### 6. 更新指标点信息
#PUT localhost:8080/api/collegeadmin/indicatorpoints/{{childPointId}}
#token: {{token}}
#Content-Type: application/json
#
#{
#  "name": "论文发表(修改后)",
#  "description": "评估学生论文发表情况(修改后)",
#  "maxScore": 25.0,
#  "itemUpperLimit": 3
#}

### 7. 尝试添加同名指标点（应失败）
#POST localhost:8080/api/collegeadmin/indicatorpoints
#token: {{token}}
#Content-Type: application/json
#
#{
#  "majorCategoryId": 101,
#  "name": "论文发表(修改后)",
#  "description": "重复名称测试",
#  "maxScore": 10.0,
#  "itemUpperLimit": 1,
#  "parentId": {{rootPointId}}
#}

### 8. 删除指标点（有子节点时应失败）
DELETE localhost:8080/api/collegeadmin/indicatorpoints/{{rootPointId}}
token: {{token}}

#### 9. 先删除子节点再删除父节点
#DELETE localhost:8080/api/collegeadmin/indicatorpoints/{{childPointId}}
#token: {{token}}
####
#DELETE localhost:8080/api/collegeadmin/indicatorpoints/{{rootPointId}}
#token: {{token}}

#### 10. 验证删除结果
#GET localhost:8080/api/collegeadmin/indicatorpoints/tree?majorCategoryId=101
#token: {{token}}