### 1. 学院管理员登录
POST localhost:8080/api/open/login
Content-Type: application/json

{
  "account": "2023221547",
  "password": "2023221547"
}

> {%
    //保存token到环境变量
    client.global.set("token", response.headers.valueOf("token"));
    client.global.set("cid", response.body.data.collegeId);
    client.log("登录成功，token: " + client.global.get("token"));
    client.log("学院ID: " + client.global.get("cid"));
%}

### 2. 获取专业类别列表
GET localhost:8080/api/collegeadmin/indicatorpoints/categories
token: {{token}}

> {%
        client.global.set("majorCategoryId", response.body.data[0].id);
%}

### 3. 添加一级指标点
POST localhost:8080/api/collegeadmin/indicatorpoints
token: {{token}}
Content-Type: application/json

{
  "majorCategoryId": {{majorCategoryId}},
  "name": "学术能力",
  "description": "评估学生的学术研究能力",
  "maxScore": 40.0,
  "itemUpperLimit": 5
}

> {%
        client.global.set("rootPointId", response.body.data.id);
%}

### 4. 添加二级指标点
POST localhost:8080/api/collegeadmin/indicatorpoints
token: {{token}}
Content-Type: application/json

{
  "majorCategoryId": {{majorCategoryId}},
  "name": "论文发表",
  "description": "评估学生论文发表情况",
  "maxScore": 20.0,
  "itemUpperLimit": 2,
  "parentId": {{rootPointId}},
  "isLeaf": false
}

> {%
        client.global.set("childPointId", response.body.data.id);
%}

### 5. 添加三级指标点（叶子节点）
POST localhost:8080/api/collegeadmin/indicatorpoints
token: {{token}}
Content-Type: application/json

{
  "majorCategoryId": {{majorCategoryId}},
  "name": "SCI论文",
  "description": "SCI期刊论文发表",
  "maxScore": 10.0,
  "itemUpperLimit": 1,
  "parentId": {{childPointId}},
  "isLeaf": true
}

> {%
        client.global.set("leafPointId", response.body.data.id);
%}

### 6. 获取树形结构
GET localhost:8080/api/collegeadmin/indicatorpoints/tree?majorCategoryId={{majorCategoryId}}
token: {{token}}



### 7. 根据类别获取指标点
GET localhost:8080/api/collegeadmin/indicatorpoints/byCategory?majorCategoryId={{majorCategoryId}}
token: {{token}}



### 8. 获取子节点列表
GET localhost:8080/api/collegeadmin/indicatorpoints/{{rootPointId}}/children
token: {{token}}


### 9. 更新指标点信息
PUT localhost:8080/api/collegeadmin/indicatorpoints/{{childPointId}}
token: {{token}}
Content-Type: application/json

{
  "majorCategoryId": {{majorCategoryId}},
  "name": "论文发表（更新）",
  "description": "评估学生论文发表情况（已更新）",
  "maxScore": 25.0,
  "itemUpperLimit": 3,
  "isLeaf": false
}



### 10. 尝试删除有子节点的指标点
DELETE localhost:8080/api/collegeadmin/indicatorpoints/{{rootPointId}}
token: {{token}}



### 11. 删除叶子节点指标点
DELETE localhost:8080/api/collegeadmin/indicatorpoints/{{leafPointId}}
token: {{token}}


### 12. 测试同名指标点
POST localhost:8080/api/collegeadmin/indicatorpoints
token: {{token}}
Content-Type: application/json

{
  "majorCategoryId": {{majorCategoryId}},
  "name": "学术能力",
  "description": "重复名称测试",
  "maxScore": 30.0,
  "itemUpperLimit": 3
}


### 13. 测试在叶子节点下添加子节点
POST localhost:8080/api/collegeadmin/indicatorpoints
token: {{token}}
Content-Type: application/json

{
  "majorCategoryId": {{majorCategoryId}},
  "name": "测试子节点",
  "description": "在叶子节点下添加子节点测试",
  "maxScore": 5.0,
  "itemUpperLimit": 1,
  "parentId": {{leafPointId}}
}



### 14. 清理测试数据
DELETE localhost:8080/api/collegeadmin/indicatorpoints/{{childPointId}}
token: {{token}}


###
DELETE localhost:8080/api/collegeadmin/indicatorpoints/{{rootPointId}}
token: {{token}}
