### 超级管理员登录
POST localhost:8080/api/open/login
Content-Type: application/json

{
  "account": "admin",
  "password": "admin"
}


### 学院管理员登录
POST localhost:8080/api/open/login
Content-Type: application/json

{
  "account": "2023221547",
  "password": "2023221547"
}