collegeadmin-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoieUhKNyIsInVpZCI6MTQyMTEzNDQxNTkwNjUyOTI4MCwiaWF0IjoxNzU4ODk3NTkxLCJleHAiOjE3NTg5ODM5OTF9.r2VYU-KgSsZfu3yLxlOIwokdyT59sueOpUKv1I0OfB4

### 用户可以修改自己的密码
PATCH localhost:8080/api/open/user/password
token: ${collegeadmin-token}
Content-Type: application/json

{
  "password": "12345678"
}